version: "3.9"  # optional since v1.27.0
services:
  react-app:
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
  
    # env_file:
    #   - ./.env